set mouse=a

" Some vim users are used to pressing Ctrl+6 to go to the alternate file, but
" this only ever worked because terminals don't distinguish it from Ctrl+^.
nnoremap <C-6> <C-^>

function MacSetFont(name, size)
    call rpcnotify(1, "set-font", a:name, a:size)
endfunction

function MacSetBackupFont(name)
    call rpcnotify(1, "set-backup-font", a:name)
endfunction
